### PR TITLE
fix issues affecting code quality

### PR DESCRIPTION
**Pull request by withshubh**
### Description
Hi :wave: 
I ran the [DeepSource](https://deepsource.io) analysis on the forked copy of this repo and found some interesting [code quality issues](https://deepsource.io/gh/withshubh/robotics-toolbox-python/issues/?category=recommended).

##### Motivation and Context
Some of the issues I have fixed boost minor performance and a few removes the anti-patterns in code.

#### Summary of changes
- Used identity check for comparison with True
- Replaced `assertEquals` with `assertEqual`
- Refactored useless `else` block in the loop
- Added the bound instance as method parameter
- Used tuple unpacking to swap variables
- Refactored unnecessary `else` / `elif` when `if` block has a `continue` statement
- Added .deepsource.toml config

### CODE REVIEW

**Comment by petercorke** [comment]
thanks for this.  A few comments:

- it might seem trivial, but we are trying to minimise the number of files in the top-level folder to the absolute minimum, keeps the start of the README visible.  Does the deepsource file have to be there?
- IK.py, what's the issue with the else clause on the for loop?  Performance or style issue?
- mobile and dhfactor are very rough WIP
- dynamixel code is borrowed from the vendor :)

**Comment by withshubh** [comment]
Hi @petercorke :wave: 
> it might seem trivial, but we are trying to minimise the number of files in the top-level folder to the absolute minimum, keeps the start of the README visible. Does the deepsource file have to be there?
- I totally understand your concern but think of the long term as the project will grow you may want to have certain tools. Integrating `.deepsource.toml` in the root of the directory will save you from adding a lot of other files. DeepSource internally runs black/isort/flake8 checks which you'll never have to add externally on this repo. Apart from continuously analyzing for code quality issues and automatically fixing them, you can use it to detect problems in dockerfiles and track the test coverage.
> IK.py, what's the issue with the else clause on the for loop? Performance or style issue?
- This is a potential bug risk. Read more about this issue [here](https://deepsource.io/gh/withshubh/robotics-toolbox-python/issue/PYL-W0120/description).
> mobile and dhfactor are very rough WIP
- Should I revert the changes?
> dynamixel code is borrowed from the vendor
- Changes reverted.

**Comment by withshubh** [comment]
Hey @petercorke :wave: 

any update?

**Comment by jhavl** [comment]
Hi @withshubh, I've been looking into automated code review tools over the past few days. It seems that deepsource offers almost the same service as LGTM does and we have already integrated our project with LGTM. LGTM also allows us to add comments in the code for to ignore certain issues so we don't need any extra top level directory files - which is a nice addition.

However, in saying that, the bug fixes are very welcome! If you remove the .deepsource.toml file I'll be happy to merge the rest in.

**Comment by withshubh** [comment]
Hey @jhavl  thanks for your response. I'm removing `.deepsource.toml` file if you don't want to try out DeepSource.

However, I want to highlight a few points which explain how DeepSource wins over LGTM:

* DeepSource [Python analyzer](https://deepsource.io/directory/analyzer/python/) detects ~558 issues [set of rules] while LGTM covers only [148 rules](https://lgtm.com/projects/g/dwisiswant0/apkleaks/queries/?pack=com.lgtm%2Fpython-queries).
* DeepSource offers an [Autofix feature ](https://deepsource.io/blog/autofix-future-of-code-reviews/)with which you can fix issues automatically in a couple of clicks. There are 88 Autofix available in Python analyzer. LGTM does not offer any sort of this feature.
* DeepSource offers [auto code formatter feature](https://deepsource.io/docs/transformer/), which helps auto transform your codebase to maintain code styling. Available for Python too. :snake: 
* DeepSource guarantees less than 5% false positives. and if you found one then there is option to report it directly from dashboard.
* Much better integration and developer experience.

**Comment by petercorke** [comment]
Hi Shubhendra,

Thanks again for your interest in our project.  There is a big burst of development happening over the next few months, so things are not as tidy as we would like them. 

Thanks also for the tip about for/else.  It’s not something I often use, and I understand better now about the limited cases where it makes sense to use.  

Peter

**Pull request merged**
